
export interface UserData {
	accountType: string,
	username: string,
	password: string,
	legalName: string,
	gimmickName: string,
	gimmickDescription: string,
	gimmickType: string,
	promoImage: string,
	socialMedia: string,
	socialMediaHandle: string,
	socialMediaLink: string,
	height: string,
	weight: string,
	hometown: string,
	dateOfBirth: Date,
	wrestlingStyle: string,
	finisher: string,
	signatureMove: string,
	entranceTheme: string,
	wrestlingStartDate: Date,
	wrestlingAchievements: string,
	wrestlingPromotion: string,
	wrestlingTrainers: string,
	wrestlingSchool: string,
	email: string,
	currentLocation: string,
	phoneNumber: string
}

export const TEST_USER_DATA: UserData[] = [
    {
        accountType: 'wrestler',
        username: 'thechamp',
        password: 'password123',
        legalName: 'John Smith',
        gimmickName: 'The Champ',
        gimmickDescription: 'Confident, never backs down from a challenge.',
        gimmickType: 'Face',
        promoImage: 'champ.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@thechamp',
        socialMediaLink: 'https://twitter.com/thechamp',
        height: '6\'2"',
        weight: '240 lbs',
        hometown: 'Chicago, IL',
        dateOfBirth: new Date('1988-05-14'),
        wrestlingStyle: 'Powerhouse',
        finisher: 'Champ Slam',
        signatureMove: 'Shoulder Tackle',
        entranceTheme: 'Champion’s Anthem',
        wrestlingStartDate: new Date('2010-03-01'),
        wrestlingAchievements: 'World Champion x3',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Mike Strong',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'champ@example.com',
        currentLocation: 'Chicago, IL',
        phoneNumber: '555-1234'
    },
    {
        accountType: 'wrestler',
        username: 'luchalibre',
        password: 'lucha2024',
        legalName: 'Carlos Rivera',
        gimmickName: 'El Águila',
        gimmickDescription: 'High-flying luchador with a mysterious past.',
        gimmickType: 'Face',
        promoImage: 'aguila.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@elaguila',
        socialMediaLink: 'https://instagram.com/elaguila',
        height: '5\'9"',
        weight: '180 lbs',
        hometown: 'Mexico City, MX',
        dateOfBirth: new Date('1992-11-02'),
        wrestlingStyle: 'Lucha Libre',
        finisher: 'Eagle Dive',
        signatureMove: 'Springboard Dropkick',
        entranceTheme: 'Flight of the Eagle',
        wrestlingStartDate: new Date('2014-06-15'),
        wrestlingAchievements: 'Tag Team Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'El Maestro',
        wrestlingSchool: 'Lucha School MX',
        email: 'aguila@example.com',
        currentLocation: 'Mexico City, MX',
        phoneNumber: '555-5678'
    },
    {
        accountType: 'manager',
        username: 'ringsidequeen',
        password: 'queenbee',
        legalName: 'Jessica Lee',
        gimmickName: 'Queen Jess',
        gimmickDescription: 'Charismatic manager with a sharp tongue.',
        gimmickType: 'Heel',
        promoImage: 'queen.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@queen_jess',
        socialMediaLink: 'https://twitter.com/queen_jess',
        height: '5\'7"',
        weight: '135 lbs',
        hometown: 'Los Angeles, CA',
        dateOfBirth: new Date('1985-08-23'),
        wrestlingStyle: 'Manager',
        finisher: 'Royal Decree',
        signatureMove: 'Slap',
        entranceTheme: 'Royal Entrance',
        wrestlingStartDate: new Date('2012-01-10'),
        wrestlingAchievements: 'Manager of the Year',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'N/A',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'queen@example.com',
        currentLocation: 'Los Angeles, CA',
        phoneNumber: '555-8765'
    },
    {
        accountType: 'wrestler',
        username: 'ironfist',
        password: 'iron2024',
        legalName: 'Derek Brown',
        gimmickName: 'Iron Fist',
        gimmickDescription: 'Stoic brawler with a devastating punch.',
        gimmickType: 'Heel',
        promoImage: 'ironfist.jpg',
        socialMedia: 'Facebook',
        socialMediaHandle: 'IronFistOfficial',
        socialMediaLink: 'https://facebook.com/ironfistofficial',
        height: '6\'0"',
        weight: '220 lbs',
        hometown: 'Pittsburgh, PA',
        dateOfBirth: new Date('1990-03-19'),
        wrestlingStyle: 'Brawler',
        finisher: 'Iron Punch',
        signatureMove: 'Spinebuster',
        entranceTheme: 'Steel Resolve',
        wrestlingStartDate: new Date('2013-09-05'),
        wrestlingAchievements: 'Intercontinental Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Steel Mike',
        wrestlingSchool: 'Steel City Gym',
        email: 'ironfist@example.com',
        currentLocation: 'Pittsburgh, PA',
        phoneNumber: '555-4321'
    },
    {
        accountType: 'wrestler',
        username: 'highflyer',
        password: 'flyhigh',
        legalName: 'Amy Chen',
        gimmickName: 'Skyfire',
        gimmickDescription: 'Fearless high-flyer with a fiery spirit.',
        gimmickType: 'Face',
        promoImage: 'skyfire.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@skyfire',
        socialMediaLink: 'https://instagram.com/skyfire',
        height: '5\'6"',
        weight: '125 lbs',
        hometown: 'San Francisco, CA',
        dateOfBirth: new Date('1995-07-30'),
        wrestlingStyle: 'High Flyer',
        finisher: 'Skyfall',
        signatureMove: 'Moonsault',
        entranceTheme: 'Fire in the Sky',
        wrestlingStartDate: new Date('2017-04-20'),
        wrestlingAchievements: 'Women’s Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Luna Blaze',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'skyfire@example.com',
        currentLocation: 'San Francisco, CA',
        phoneNumber: '555-2468'
    },
    {
        accountType: 'wrestler',
        username: 'submissionking',
        password: 'tapout',
        legalName: 'Victor Hayes',
        gimmickName: 'The Submission King',
        gimmickDescription: 'Technical master, makes opponents tap.',
        gimmickType: 'Heel',
        promoImage: 'submissionking.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@subking',
        socialMediaLink: 'https://twitter.com/subking',
        height: '6\'1"',
        weight: '210 lbs',
        hometown: 'Boston, MA',
        dateOfBirth: new Date('1987-12-11'),
        wrestlingStyle: 'Technical',
        finisher: 'Royal Lock',
        signatureMove: 'Armbar',
        entranceTheme: 'King’s March',
        wrestlingStartDate: new Date('2009-08-12'),
        wrestlingAchievements: 'Submission Specialist Award',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Professor Pain',
        wrestlingSchool: 'Boston Grapple',
        email: 'subking@example.com',
        currentLocation: 'Boston, MA',
        phoneNumber: '555-1357'
    },
    {
        accountType: 'wrestler',
        username: 'maskedmystery',
        password: 'mysteryman',
        legalName: 'Unknown',
        gimmickName: 'The Masked Mystery',
        gimmickDescription: 'Identity hidden, unpredictable in the ring.',
        gimmickType: 'Tweener',
        promoImage: 'masked.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@maskedmystery',
        socialMediaLink: 'https://instagram.com/maskedmystery',
        height: '5\'10"',
        weight: '200 lbs',
        hometown: 'Unknown',
        dateOfBirth: new Date('1993-01-01'),
        wrestlingStyle: 'Hybrid',
        finisher: 'Mystery Driver',
        signatureMove: 'Enzuigiri',
        entranceTheme: 'Unknown Shadows',
        wrestlingStartDate: new Date('2015-10-31'),
        wrestlingAchievements: 'Battle Royal Winner',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Unknown',
        wrestlingSchool: 'Unknown',
        email: 'masked@example.com',
        currentLocation: 'Unknown',
        phoneNumber: '555-0000'
    },
    {
        accountType: 'wrestler',
        username: 'hardcorehero',
        password: 'hardcore1',
        legalName: 'Sam Carter',
        gimmickName: 'Hardcore Hero',
        gimmickDescription: 'Tough as nails, thrives in extreme matches.',
        gimmickType: 'Face',
        promoImage: 'hardcore.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@hardcorehero',
        socialMediaLink: 'https://twitter.com/hardcorehero',
        height: '6\'3"',
        weight: '250 lbs',
        hometown: 'Detroit, MI',
        dateOfBirth: new Date('1984-04-17'),
        wrestlingStyle: 'Hardcore',
        finisher: 'Steel Chair Smash',
        signatureMove: 'DDT',
        entranceTheme: 'No Rules',
        wrestlingStartDate: new Date('2007-02-14'),
        wrestlingAchievements: 'Hardcore Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Tommy Extreme',
        wrestlingSchool: 'Detroit Dojo',
        email: 'hardcore@example.com',
        currentLocation: 'Detroit, MI',
        phoneNumber: '555-7890'
    },
    {
        accountType: 'wrestler',
        username: 'rookie',
        password: 'rookie2024',
        legalName: 'Ben Young',
        gimmickName: 'The Rookie',
        gimmickDescription: 'Eager newcomer with lots to prove.',
        gimmickType: 'Face',
        promoImage: 'rookie.jpg',
        socialMedia: 'Facebook',
        socialMediaHandle: 'RookieBen',
        socialMediaLink: 'https://facebook.com/rookieben',
        height: '5\'11"',
        weight: '190 lbs',
        hometown: 'Orlando, FL',
        dateOfBirth: new Date('2000-09-09'),
        wrestlingStyle: 'All-Rounder',
        finisher: 'Rookie Rollup',
        signatureMove: 'Dropkick',
        entranceTheme: 'New Beginnings',
        wrestlingStartDate: new Date('2023-01-01'),
        wrestlingAchievements: 'Rookie of the Year',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Coach Carter',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'rookie@example.com',
        currentLocation: 'Orlando, FL',
        phoneNumber: '555-2460'
    },
    {
        accountType: 'wrestler',
        username: 'veteran',
        password: 'veteran2024',
        legalName: 'Rick Masters',
        gimmickName: 'The Veteran',
        gimmickDescription: 'Wise, experienced, respected by all.',
        gimmickType: 'Face',
        promoImage: 'veteran.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@theveteran',
        socialMediaLink: 'https://twitter.com/theveteran',
        height: '6\'0"',
        weight: '225 lbs',
        hometown: 'Dallas, TX',
        dateOfBirth: new Date('1975-02-28'),
        wrestlingStyle: 'Technical',
        finisher: 'Master Lock',
        signatureMove: 'Suplex',
        entranceTheme: 'Legacy',
        wrestlingStartDate: new Date('1995-05-10'),
        wrestlingAchievements: 'Hall of Fame',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Old School Joe',
        wrestlingSchool: 'Dallas Wrestling School',
        email: 'veteran@example.com',
        currentLocation: 'Dallas, TX',
        phoneNumber: '555-1122'
    },
    {
        accountType: 'wrestler',
        username: 'heelheat',
        password: 'heat2024',
        legalName: 'Tony Blaze',
        gimmickName: 'Blaze',
        gimmickDescription: 'Cocky heel who loves to taunt the crowd.',
        gimmickType: 'Heel',
        promoImage: 'blaze.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@blaze',
        socialMediaLink: 'https://instagram.com/blaze',
        height: '6\'1"',
        weight: '215 lbs',
        hometown: 'Las Vegas, NV',
        dateOfBirth: new Date('1991-06-06'),
        wrestlingStyle: 'Showman',
        finisher: 'Blaze Bomb',
        signatureMove: 'Superkick',
        entranceTheme: 'Burn It Down',
        wrestlingStartDate: new Date('2012-11-11'),
        wrestlingAchievements: 'TV Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Flash Gordon',
        wrestlingSchool: 'Vegas Wrestling School',
        email: 'blaze@example.com',
        currentLocation: 'Las Vegas, NV',
        phoneNumber: '555-3344'
    },
    {
        accountType: 'wrestler',
        username: 'powerhouse',
        password: 'power2024',
        legalName: 'Linda Power',
        gimmickName: 'Powerhouse',
        gimmickDescription: 'Dominant force, unmatched strength.',
        gimmickType: 'Face',
        promoImage: 'powerhouse.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@powerhouse',
        socialMediaLink: 'https://twitter.com/powerhouse',
        height: '5\'10"',
        weight: '180 lbs',
        hometown: 'Houston, TX',
        dateOfBirth: new Date('1989-10-10'),
        wrestlingStyle: 'Powerhouse',
        finisher: 'Power Slam',
        signatureMove: 'Clothesline',
        entranceTheme: 'Unstoppable',
        wrestlingStartDate: new Date('2011-07-07'),
        wrestlingAchievements: 'Women’s Tag Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Big Sue',
        wrestlingSchool: 'Houston Power Gym',
        email: 'powerhouse@example.com',
        currentLocation: 'Houston, TX',
        phoneNumber: '555-5566'
    },
    {
        accountType: 'wrestler',
        username: 'submissionqueen',
        password: 'queen2024',
        legalName: 'Rachel Evans',
        gimmickName: 'Submission Queen',
        gimmickDescription: 'Submission specialist, never gives up.',
        gimmickType: 'Face',
        promoImage: 'submissionqueen.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@subqueen',
        socialMediaLink: 'https://instagram.com/subqueen',
        height: '5\'8"',
        weight: '140 lbs',
        hometown: 'Seattle, WA',
        dateOfBirth: new Date('1994-03-03'),
        wrestlingStyle: 'Technical',
        finisher: 'Queen’s Clutch',
        signatureMove: 'Triangle Choke',
        entranceTheme: 'Royalty',
        wrestlingStartDate: new Date('2016-09-09'),
        wrestlingAchievements: 'Women’s Submission Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Professor Pain',
        wrestlingSchool: 'Seattle Grapple',
        email: 'subqueen@example.com',
        currentLocation: 'Seattle, WA',
        phoneNumber: '555-7788'
    },
    {
        accountType: 'wrestler',
        username: 'giant',
        password: 'giant2024',
        legalName: 'George Grant',
        gimmickName: 'The Giant',
        gimmickDescription: 'Towering giant, unstoppable in the ring.',
        gimmickType: 'Heel',
        promoImage: 'giant.jpg',
        socialMedia: 'Facebook',
        socialMediaHandle: 'TheGiant',
        socialMediaLink: 'https://facebook.com/thegiant',
        height: '7\'0"',
        weight: '350 lbs',
        hometown: 'Denver, CO',
        dateOfBirth: new Date('1982-12-25'),
        wrestlingStyle: 'Powerhouse',
        finisher: 'Giant Chokeslam',
        signatureMove: 'Big Boot',
        entranceTheme: 'Earthquake',
        wrestlingStartDate: new Date('2005-05-05'),
        wrestlingAchievements: 'Battle Royal Winner',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Big Mike',
        wrestlingSchool: 'Denver Wrestling School',
        email: 'giant@example.com',
        currentLocation: 'Denver, CO',
        phoneNumber: '555-9900'
    },
    {
        accountType: 'wrestler',
        username: 'technician',
        password: 'tech2024',
        legalName: 'Elliot Reed',
        gimmickName: 'The Technician',
        gimmickDescription: 'Outwits opponents with technical prowess.',
        gimmickType: 'Face',
        promoImage: 'technician.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@technician',
        socialMediaLink: 'https://twitter.com/technician',
        height: '5\'11"',
        weight: '200 lbs',
        hometown: 'Minneapolis, MN',
        dateOfBirth: new Date('1990-01-20'),
        wrestlingStyle: 'Technical',
        finisher: 'Tech Lock',
        signatureMove: 'German Suplex',
        entranceTheme: 'Precision',
        wrestlingStartDate: new Date('2012-03-03'),
        wrestlingAchievements: 'Technical Wrestler Award',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Professor Pain',
        wrestlingSchool: 'Minneapolis Mat Club',
        email: 'technician@example.com',
        currentLocation: 'Minneapolis, MN',
        phoneNumber: '555-2233'
    },
    {
        accountType: 'wrestler',
        username: 'wildcard',
        password: 'wild2024',
        legalName: 'Zoe Wild',
        gimmickName: 'Wildcard',
        gimmickDescription: 'Unpredictable, always keeps opponents guessing.',
        gimmickType: 'Tweener',
        promoImage: 'wildcard.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@wildcard',
        socialMediaLink: 'https://instagram.com/wildcard',
        height: '5\'5"',
        weight: '130 lbs',
        hometown: 'Phoenix, AZ',
        dateOfBirth: new Date('1997-04-04'),
        wrestlingStyle: 'Hybrid',
        finisher: 'Wild Ride',
        signatureMove: 'Corkscrew Neckbreaker',
        entranceTheme: 'Chaos',
        wrestlingStartDate: new Date('2018-08-08'),
        wrestlingAchievements: 'Breakout Star',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Luna Blaze',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'wildcard@example.com',
        currentLocation: 'Phoenix, AZ',
        phoneNumber: '555-8899'
    },
    {
        accountType: 'wrestler',
        username: 'brawler',
        password: 'brawl2024',
        legalName: 'Frank Stone',
        gimmickName: 'Stone',
        gimmickDescription: 'Hard-hitting brawler, never backs down.',
        gimmickType: 'Heel',
        promoImage: 'stone.jpg',
        socialMedia: 'Facebook',
        socialMediaHandle: 'StoneBrawler',
        socialMediaLink: 'https://facebook.com/stonebrawler',
        height: '6\'2"',
        weight: '240 lbs',
        hometown: 'Cleveland, OH',
        dateOfBirth: new Date('1986-06-16'),
        wrestlingStyle: 'Brawler',
        finisher: 'Stone Breaker',
        signatureMove: 'Lariat',
        entranceTheme: 'Stone Cold',
        wrestlingStartDate: new Date('2008-10-10'),
        wrestlingAchievements: 'Tag Team Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Iron Mike',
        wrestlingSchool: 'Cleveland Wrestling School',
        email: 'stone@example.com',
        currentLocation: 'Cleveland, OH',
        phoneNumber: '555-6677'
    },
    {
        accountType: 'wrestler',
        username: 'showstopper',
        password: 'show2024',
        legalName: 'Mia Starr',
        gimmickName: 'Showstopper',
        gimmickDescription: 'Steals the show with every performance.',
        gimmickType: 'Face',
        promoImage: 'showstopper.jpg',
        socialMedia: 'Twitter',
        socialMediaHandle: '@showstopper',
        socialMediaLink: 'https://twitter.com/showstopper',
        height: '5\'7"',
        weight: '135 lbs',
        hometown: 'Miami, FL',
        dateOfBirth: new Date('1993-12-12'),
        wrestlingStyle: 'Showman',
        finisher: 'Starr Power',
        signatureMove: 'Diving Elbow',
        entranceTheme: 'Spotlight',
        wrestlingStartDate: new Date('2015-05-05'),
        wrestlingAchievements: 'Women’s Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Luna Blaze',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'showstopper@example.com',
        currentLocation: 'Miami, FL',
        phoneNumber: '555-7789'
    },
    {
        accountType: 'wrestler',
        username: 'underdog',
        password: 'underdog2024',
        legalName: 'Chris Lane',
        gimmickName: 'The Underdog',
        gimmickDescription: 'Always fights from underneath, never gives up.',
        gimmickType: 'Face',
        promoImage: 'underdog.jpg',
        socialMedia: 'Instagram',
        socialMediaHandle: '@underdog',
        socialMediaLink: 'https://instagram.com/underdog',
        height: '5\'8"',
        weight: '160 lbs',
        hometown: 'Portland, OR',
        dateOfBirth: new Date('1998-02-02'),
        wrestlingStyle: 'All-Rounder',
        finisher: 'Comeback Kid',
        signatureMove: 'Crossbody',
        entranceTheme: 'Against All Odds',
        wrestlingStartDate: new Date('2021-03-03'),
        wrestlingAchievements: 'Fan Favorite',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Coach Carter',
        wrestlingSchool: 'Kayfabe Academy',
        email: 'underdog@example.com',
        currentLocation: 'Portland, OR',
        phoneNumber: '555-4455'
    },
    {
        accountType: 'wrestler',
        username: 'enforcer',
        password: 'enforce2024',
        legalName: 'Mark Justice',
        gimmickName: 'The Enforcer',
        gimmickDescription: 'Law and order in the ring.',
        gimmickType: 'Heel',
        promoImage: 'enforcer.jpg',
        socialMedia: 'Facebook',
        socialMediaHandle: 'EnforcerMark',
        socialMediaLink: 'https://facebook.com/enforcermark',
        height: '6\'4"',
        weight: '260 lbs',
        hometown: 'Atlanta, GA',
        dateOfBirth: new Date('1983-11-11'),
        wrestlingStyle: 'Powerhouse',
        finisher: 'Justice Slam',
        signatureMove: 'Big Boot',
        entranceTheme: 'Order Restored',
        wrestlingStartDate: new Date('2006-06-06'),
        wrestlingAchievements: 'Security Champion',
        wrestlingPromotion: 'Kayfabe Pro',
        wrestlingTrainers: 'Big Mike',
        wrestlingSchool: 'Atlanta Wrestling School',
        email: 'enforcer@example.com',
        currentLocation: 'Atlanta, GA',
        phoneNumber: '555-9911'
    }
];
